# Site settings
title: Блог Оли
header-img: img/home-bg.jpg
email: mika.smith@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"

baseurl: "http://olyakoval.in.ua"
url: ""

twitter_username: 
github_username: shivasena
facebook_username: aurea.olya

# Build settings
encoding: utf-8
markdown: kramdown
highlighter: pygments
permalink: /blog/:title
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]