# Site settings
title: Олин Блог
header-img: img/home-bg.jpg
email: mika.smith@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"

baseurl: "/cleanblog"
url: "http://shivasena.github.io/"

twitter_username: 
github_username: shivasena
facebook_username: mi.koval

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
